spring:
  application:
    name: HomeFinance
  datasource:
    url: ${POSTGRES_HOST}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration
    url: ${POSTGRES_HOST}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    #    show-sql: true
  web:
    resources:
      add-mappings: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SUPABASE_PROJECT_URL}/auth/v1

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

supabase:
  url: ${SUPABASE_PROJECT_URL}
  api:
    key: ${SUPABASE_PUBLIC_API_KEY}
    secret-key: ${SUPABASE_SECRET_API_KEY}
logging:
  level:
    com.example.demo: "INFO"
    org.springframework: "INFO"
    org.springframework.cache: "INFO"
    org.springframework.security: "INFO"
    org.springframework.security.oauth2: "INFO"
    org.springframework.web: "INFO"


server:
  port: ${SERVER_PORT:80}